#!/bin/bash
# 展示所有功能

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  🎬 漫画短剧生成系统 - 完整功能展示"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "📚 已创建的文件:"
echo ""
echo "  核心模块:"
echo "    ✅ src/generators/nano_banana_generator.py   (Nano Banana图像生成)"
echo "    ✅ src/generators/video_composer.py          (视频合成+字幕)"
echo "    ✅ src/generators/tts_generator.py           (ElevenLabs配音)"
echo "    ✅ src/generators/audio_mixer.py             (音频混合)"
echo ""
echo "  剧本库:"
echo "    🐺 scripts/werewolf_game_scripts.py          (4个狼人杀剧本)"
echo "    🎨 scripts/example_scripts.py                (4个通用剧本)"
echo ""
echo "  生成脚本:"
echo "    ⚡ scripts/generate_werewolf_drama.py        (狼人杀专用)"
echo "    ⚡ scripts/generate_comic_drama.py           (通用生成)"
echo "    🧪 scripts/test_comic_generation.py          (测试套件)"
echo ""
echo "  文档:"
echo "    📖 QUICKSTART_WEREWOLF.md                    (3分钟快速开始)"
echo "    📖 docs/WEREWOLF_DRAMA_GUIDE.md              (详细指南)"
echo "    📖 docs/COMIC_DRAMA_QUICKSTART.md            (通用指南)"
echo "    📖 USAGE_EXAMPLES.md                         (15个使用示例)"
echo ""
echo "  配置:"
echo "    ⚙️ config/comic.yaml                         (漫画/视频配置)"
echo "    ⚙️ .env.example                              (API Keys模板)"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "🚀 快速开始（3步）:"
echo ""
echo "  1️⃣ 安装依赖:"
echo "     pip install -r requirements.txt"
echo ""
echo "  2️⃣ 配置API Keys:"
echo "     cp .env.example .env"
echo "     # 编辑 .env，添加 GOOGLE_API_KEY 和 ELEVENLABS_API_KEY"
echo ""
echo "  3️⃣ 生成第一个视频:"
echo "     python scripts/generate_werewolf_drama.py"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "📚 详细文档:"
echo ""
echo "  • 阅读快速开始: cat QUICKSTART_WEREWOLF.md"
echo "  • 查看所有功能: python scripts/show_all_features.py"
echo "  • 查看使用示例: cat USAGE_EXAMPLES.md"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
