/**
 * TeamVenture Design Tokens
 * 自动生成，请勿手动修改
 * 生成时间: 2026-01-05T18:09:15.620Z
 */

const DESIGN_TOKENS = {
  globalColorsPrimary: '#1890ff',
  globalColorsPrimaryDark: '#096dd9',
  globalColorsPrimaryLight: '#e6f7ff',
  globalColorsSuccess: '#52c41a',
  globalColorsSuccessLight: '#f6ffed',
  globalColorsWarning: '#faad14',
  globalColorsWarningLight: '#fffbe6',
  globalColorsDanger: '#f5222d',
  globalColorsDangerLight: '#fff1f0',
  globalColorsPurpleStart: '#667eea',
  globalColorsPurpleEnd: '#764ba2',
  globalNeutralsTitle: '#333333',
  globalNeutralsText: '#666666',
  globalNeutralsSecondary: '#999999',
  globalNeutralsBorder: '#e8e8e8',
  globalNeutralsDivider: '#f0f0f0',
  globalNeutralsBackground: '#f5f5f5',
  globalNeutralsCard: '#ffffff',
  globalTypographyFontFamily: '-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', sans-serif',
  globalTypographyFontSizeXs: '20rpx',
  globalTypographyFontSizeSm: '24rpx',
  globalTypographyFontSizeBase: '28rpx',
  globalTypographyFontSizeMd: '32rpx',
  globalTypographyFontSizeLg: '36rpx',
  globalTypographyFontSizeXl: '44rpx',
  globalTypographyFontWeightNormal: '400',
  globalTypographyFontWeightMedium: '500',
  globalTypographyFontWeightBold: '600',
  globalSpacingXs: '8rpx',
  globalSpacingSm: '16rpx',
  globalSpacingMd: '24rpx',
  globalSpacingBase: '32rpx',
  globalSpacingLg: '48rpx',
  globalSpacingXl: '64rpx',
  globalBorderradiusSm: '8rpx',
  globalBorderradiusBase: '16rpx',
  globalBorderradiusLg: '24rpx',
  globalBorderradiusXl: '32rpx',
  globalBorderradiusFull: '9999rpx',
  globalShadowsSm: '0 2rpx 8rpx rgba(0, 0, 0, 0.08)',
  globalShadowsBase: '0 4rpx 16rpx rgba(0, 0, 0, 0.12)',
  globalShadowsLg: '0 8rpx 32rpx rgba(0, 0, 0, 0.16)',
  componentsButtonPrimaryBackground: '#1890ff',
  componentsButtonPrimaryText: '#ffffff',
  componentsButtonPrimaryBorderRadius: '24rpx',
  componentsButtonSecondaryBackground: '#ffffff',
  componentsButtonSecondaryText: '#1890ff',
  componentsButtonSecondaryBorder: '#1890ff',
  componentsButtonDangerBackground: '#f5222d',
  componentsButtonDangerText: '#ffffff',
  componentsCardBackground: '#ffffff',
  componentsCardBorderRadius: '24rpx',
  componentsCardShadow: '0 4rpx 16rpx rgba(0, 0, 0, 0.12)',
  componentsCardPadding: '32rpx',
  componentsInputBackground: '#f5f5f5',
  componentsInputBorder: '#e8e8e8',
  componentsInputBorderFocus: '#1890ff',
  componentsInputPlaceholder: '#999999',
  componentsInputBorderRadius: '16rpx',
  componentsNavigationBarBackground: '#1890ff',
  componentsNavigationBarText: '#ffffff',
  componentsNavigationTabActive: '#1890ff',
  componentsNavigationTabInactive: '#999999',
  componentsStatusGeneratingBackground: '#e6f7ff',
  componentsStatusGeneratingText: '#1890ff',
  componentsStatusCompletedBackground: '#f6ffed',
  componentsStatusCompletedText: '#52c41a',
  componentsStatusFailedBackground: '#fff1f0',
  componentsStatusFailedText: '#f5222d',
  pagesLoginGradientStart: '#667eea',
  pagesLoginGradientEnd: '#764ba2',
  pagesLoginCardBackground: 'rgba(255, 255, 255, 0.95)',
  pagesFormHeaderBackground: '#1890ff',
  pagesFormStepActive: '#1890ff',
  pagesFormStepCompleted: '#52c41a',
  pagesFormStepPending: '#e8e8e8',
};

module.exports = DESIGN_TOKENS;
