openapi: 3.0.0
info:
  title: TeamVenture Tutorial API
  version: 1.0.0
  description: API for Corporate Event Booking System

paths:
  /sessions:
    get:
      summary: List available sessions
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [PUBLISHED, FULL, COMPLETED]
      responses:
        '200':
          description: List of sessions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SessionDTO'

  /bookings:
    post:
      summary: Create a booking (Join a session)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [sessionId, employeeId]
              properties:
                sessionId:
                  type: integer
                  format: int64
                employeeId:
                  type: integer
                  format: int64
      responses:
        '200':
          description: Booking result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingResultDTO'
        '400':
          description: Business Error (e.g. Already Booked, Session Ended)

components:
  schemas:
    SessionDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        startTime:
          type: string
          format: date-time
        bookedCount:
          type: integer
        maxCapacity:
          type: integer
        status:
          type: string
          enum: [PUBLISHED, FULL, CANCELLED]

    BookingResultDTO:
      type: object
      properties:
        bookingId:
          type: integer
          format: int64
        status:
          type: string
          enum: [CONFIRMED, WAITING]
          description: "CONFIRMED if stock was available, WAITING if moved to waitlist"
        queuePosition:
          type: integer
          description: "Only present if status is WAITING"
