#!/bin/bash
# 手动部署步骤指南
# 执行落地部署到 TOMO 服务器

echo "=========================================="
echo "手动部署步骤 - TOMO 服务器落地"
echo "=========================================="
echo ""

echo "步骤 1: 连接到 TOMO 服务器"
echo "----------------------------------------"
echo "# 连接服务器"
echo "ssh root@agent.tomo-ai.cn"
echo ""
echo "# 输入跳板机 OTP + 目标服务器密码"
echo ""

echo "步骤 2: 创建应用目录结构"
echo "----------------------------------------"
echo "# 在服务器上执行以下命令"
echo ""
echo "# 创建应用目录"
echo "mkdir -p /root/apps"
echo "cd /root/apps"
echo ""
echo "# 创建服务目录"
echo "mkdir -p nginx teamventure zhimeng-agent"
echo ""

echo "步骤 3: 同步配置文件"
echo "----------------------------------------"
echo "# 在本地执行以下命令同步文件"
echo ""
echo "# 同步 Nginx 配置"
echo "rsync -avz apps/nginx/ root@agent.tomo-ai.cn:/root/apps/nginx/"
echo ""
echo "# 同步 TeamVenture 配置"
echo "rsync -avz apps/teamventure/ root@agent.tomo-ai.cn:/root/apps/teamventure/"
echo ""
echo "# 同步 Zhimeng Agent 配置"
echo "rsync -avz apps/zhimeng-agent/ root@agent.tomo-ai.cn:/root/apps/zhimeng-agent/"
echo ""

echo "步骤 4: 服务器端部署"
echo "----------------------------------------"
echo "# 返回到服务器终端，继续执行"
echo ""
echo "cd /root/apps"
echo ""
echo "# 创建共享网络"
echo "docker network create apps-shared-network 2>/dev/null || echo '网络已存在'"
echo ""
echo "# 启动 Nginx 网关"
echo "cd nginx"
echo "docker compose down 2>/dev/null || true"
echo "docker compose up -d"
echo "docker compose ps"
echo ""
echo "# 启动 TeamVenture 应用"
echo "cd ../teamventure/src"
echo "make down 2>/dev/null || true"
echo "make up"
echo "make status"
echo ""
echo "# 启动 Zhimeng Agent"
echo "cd ../../zhimeng-agent"
echo "docker compose down 2>/dev/null || true"
echo "docker compose up -d"
echo "docker compose ps"
echo ""

echo "步骤 5: 验证部署"
echo "----------------------------------------"
echo "# 检查所有服务状态"
echo "docker ps --format \"table {{.Names}}\t{{.Status}}\t{{.Ports}}\""
echo ""
echo "# 测试服务访问"
echo "curl -s http://localhost | jq ."
echo "curl -s http://localhost/actuator/health"
echo ""

echo "=========================================="
echo "服务访问地址"
echo "=========================================="
echo ""
echo "Nginx 网关:         http://agent.tomo-ai.cn"
echo "TeamVenture API:    http://agent.tomo-ai.cn/api/v1/"
echo "AI 服务:           http://agent.tomo-ai.cn/ai/"
echo "XHS 抓取服务:       http://agent.tomo-ai.cn/xhs/"
echo "Zhimeng Agent:      http://agent.tomo-ai.cn:8001"
echo ""

echo "=========================================="
echo "管理命令"
echo "=========================================="
echo ""
echo "# 查看状态"
echo "ssh root@agent.tomo-ai.cn 'docker ps'"
echo ""
echo "# 查看日志"
echo "ssh root@agent.tomo-ai.cn 'cd /root/apps/teamventure/src && make logs'"
echo ""
echo "# 重启服务"
echo "ssh root@agent.tomo-ai.cn '/root/apps/start-all-services.sh'"
echo ""
echo "# 停止服务"
echo "ssh root@agent.tomo-ai.cn '/root/apps/stop-all-services.sh'"
echo ""

echo "=========================================="
echo "完成！"
echo "=========================================="